name: Deploy Production Bot to Server

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/megabot-prod
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            git reset --hard
            git fetch
            git checkout origin/master
            pm2 flush megabot-prod
            yarn install --production --check-files
            pm2 stop megabot-prod; pm2 delete megabot-prod; pm2 start yarn --interpreter bash --name megabot-prod -- start; pm2 restart megabot-prod --cron-restart="0 0 * * *"
