name: Deploy Development Bot to Server

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/megabot-dev
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            git reset --hard
            git fetch
            git checkout origin/development
            pm2 flush megabot-dev
            yarn install --production --check-files
            pm2 stop megabot-dev; pm2 start yarn --interpreter bash --cron-restart="0 0 * * *" --name megabot-dev -- start
