name: CI

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install 1.63 toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.63.0
          components: rustfmt, clippy

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo check
        run: cargo check

      - name: Run cargo clippy
        run: cargo clippy -- --deny warnings

      - name: Run cargo test
        run: cargo test
